version: "2"

services:

  influxdb:
    extends:
      file: common.yml
      service: influxdb

  grafana:
    extends:
      file: common.yml
      service: grafana
    depends_on:
      - influxdb

  speedy:
    build:
      context: ./docker/speedy
      dockerfile: Dockerfile
    env_file:
      - ./configuration.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - influxdb
    command: ["yarn", "run", "start"]

volumes:
  influxdb_data: {}
  grafana_data: {}
