version: "2"

services:

  influxdb:
    extends:
      file: common.yml
      service: hypriot/influxdb

  grafana:
    extends:
      file: common.yml
      service: grafana
    depends_on:
      - influxdb

  speedy:
    build:
      context: ./docker/speedy
      dockerfile: Dockerfile
    env_file:
      - ./configuration.env
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./docker/speedy/:/home/
    depends_on:
      - influxdb
    command: ["yarn", "run", "start:dev"]


volumes:
  influxdb_data: {}
  grafana_data: {}
